export const INIT_APP = 'APP/INIT_APP'
export const SHOW_LOADING = 'APP/SHOW_LOADING'
export const HIDE_LOADING = 'APP/HIDE_LOADING'
export const UPDATE_PROGRESS_LOADING = 'APP/UPDATE_PROGRESS_LOADING'